;;; CUSTOM SET VARIABLES
(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(auto-compression-mode t nil (jka-compr))
 '(auto-image-file-mode t)
 '(blink-cursor-mode nil)
 '(browse-url-browser-function (quote browse-url-firefox))
 '(case-fold-search t)
 '(compilation-ask-about-save nil)
 '(compilation-read-command nil)
 '(compilation-scroll-output t)
 '(current-language-environment "English")
 '(desktop-enable t)
 '(dired-dwim-target t)
 '(ecb-options-version "2.32")
 '(ecb-source-path (quote ("/home/jlouis/hacking")))
 '(global-font-lock-mode t nil (font-lock))
 '(haskell-program-name "ghci")
 '(indicate-empty-lines t)
 '(js2-basic-offset 4)
 '(quack-default-program "scheme48")
 '(quack-fontify-style (quote emacs))
 '(safe-local-variable-values (quote ((Syntax . Common-lisp))))
 '(scheme-program-name "scheme48")
 '(show-paren-mode t nil (paren))
 '(show-trailing-whitespace t)
 '(slime-startup-animation nil)
 '(sml-compile-command "CM.make \"sources.cm\"")
 '(sml-indent-args 2)
 '(sml-indent-level 2)
 '(speedbar-frame-parameters (quote ((minibuffer) (width . 20) (border-width . 0) (menu-bar-lines . 0) (tool-bar-lines . 0) (unsplittable . t) (set-background-color "black"))))
 '(speedbar-show-unknown-files t)
 '(user-mail-address "jesper.louis.andersen@gmail.com")
 '(visible-bell t))
